name: Nuget Pack and Push
run-name: nuget package 🚀
on:
    workflow_dispatch:
jobs:
  nuget-pack-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Nuget package
        run: |
            nuget pack './nuget-package/pack.nuspec'
      - run: |
            dotnet nuget push './nuget-package/*.nupkg' --source "github" --api-key ${{ secrets.REPOS_READ_TOKEN }}
